import { useMemo } from "react"
import { useTranslation } from "react-i18next"

const JA = {
	sections: [
		{ id: "query-s01", num: "01", label: "背景", labelFull: "要請背景" },
		{ id: "query-s02", num: "02", label: "定義", labelFull: "定義・役割" },
		{ id: "query-s03", num: "03", label: "市場", labelFull: "市場規模" },
		{ id: "query-s04", num: "04", label: "歴史", labelFull: "技術史年表" },
		{ id: "query-s05", num: "05", label: "構造", labelFull: "技術構造" },
		{ id: "query-s06", num: "06", label: "課題", labelFull: "課題" },
		{ id: "query-s07", num: "07", label: "支援", labelFull: "公的支援" },
	],
	readingGuideTitle: "読み方ガイド",
	readingGuide:
		"このクエリレポートは、検索クエリに対する全体地図です。要請背景・定義・市場規模・技術史・原理構造・課題・公的支援の順で読むことで、テーマの妥当性と参入機会の輪郭を素早く把握できます。次のステップへ進む前に、各セクションをスキャンしてクエリの方向性を確認してください。",
	toc: "目次",
	queryReportTitle: "Query Report — クエリレポート",
	sources: "出典・参考資料",
	confidence: { high: "信頼度：高", medium: "信頼度：中", low: "信頼度：低" },
	sectionPoint: "このセクションのポイント",
	section01: { policyTrends: "主要国の政策動向", openSource: "出典を開く" },
	section02: {
		definition: "定義",
		advantages: "技術的優位性",
		sourceStrength: "元特性名：",
	},
	section03: {
		title: "市場規模",
		tam: "TAM — 上位カテゴリ市場",
		forecastComparison: "主要市場予測の比較",
		org: "調査機関",
		marketForecast: "市場規模予測",
		forecastYear: "予測年",
		scenario: {
			"base-case": "ベース",
			optimistic: "強気",
			conservative: "保守",
		},
	},
	section04: {
		title: "技術史年表",
		searchKeywords: "使用した検索キーワード",
		phases: "技術発展のフェーズ",
		annualTrend: "論文・特許の年次推移",
		year: "年",
		papers: "論文数",
		patents: "特許数",
		events: "主要イベント",
		eventTimeline: "主要イベント年表",
		keyPapers: "主要論文",
		topAssignees: "主要特許出願人",
		dataSource: "データソース：",
		openDoi: "DOIリンクを開く",
	},
	section05: {
		title: "技術構造（原理の構造化）",
		commercialized: "A 商用化",
		demonstrated: "B 実証",
		basicResearch: "C 基礎研究",
		blank: "D 空白",
		notViable: "E 不成立",
		principleMapRef: "原理マップ参照：",
		scope: "スコープ宣言",
		broadDef: "広義の定義",
		narrowDef: "本分析の狭義",
		adoptedScope: "採用スコープ",
		excluded: "除外した隣接技術",
		mechanismAndSubprocess: "中心メカニズムとサブプロセス",
		centralMechanism: "中心メカニズム",
		required: "必須",
		optional: "任意",
		principleAxes: "原理軸（直積空間の構築）",
		linkedSubprocess: "対応サブプロセス",
		principleMap: "原理マップ",
		combinations: "通りの組み合わせ",
		selectBadge: "分類バッジを選ぶと、該当する組み合わせが表示されます。",
		trlDefs: "TRL（技術成熟度）の定義",
		trlAssessment: "技術方式のTRL評価",
	},
	section06: {
		title: "課題",
		mainChallenges: "主要課題",
		barrier: "障壁：",
		risk: {
			tech: "技術",
			economic: "経済",
			regulatory: "規制",
			social: "社会",
			geopolitical: "地政学",
		},
	},
	section07: {
		title: "公的支援",
		programs: "活用可能な公的支援制度",
		openApply: "申請ページを開く",
	},
}

const EN: typeof JA = {
	sections: [
		{
			id: "query-s01",
			num: "01",
			label: "Background",
			labelFull: "Background",
		},
		{
			id: "query-s02",
			num: "02",
			label: "Definition",
			labelFull: "Definition & Role",
		},
		{ id: "query-s03", num: "03", label: "Market", labelFull: "Market Size" },
		{
			id: "query-s04",
			num: "04",
			label: "History",
			labelFull: "Technology Timeline",
		},
		{
			id: "query-s05",
			num: "05",
			label: "Structure",
			labelFull: "Technology Structure",
		},
		{
			id: "query-s06",
			num: "06",
			label: "Challenges",
			labelFull: "Challenges",
		},
		{
			id: "query-s07",
			num: "07",
			label: "Support",
			labelFull: "Public Support",
		},
	],
	readingGuideTitle: "Reading Guide",
	readingGuide:
		"This query report is a map of the search query. Scan the background, definition, market size, technology history, principle structure, challenges, and public support to understand the theme's validity and opportunity space before moving to the next step.",
	toc: "Contents",
	queryReportTitle: "Query Report",
	sources: "Sources",
	confidence: {
		high: "Confidence: High",
		medium: "Confidence: Medium",
		low: "Confidence: Low",
	},
	sectionPoint: "Key Point",
	section01: {
		policyTrends: "Policy Trends by Major Region",
		openSource: "Open source",
	},
	section02: {
		definition: "Definition",
		advantages: "Technical Advantages",
		sourceStrength: "Source strength: ",
	},
	section03: {
		title: "Market Size",
		tam: "TAM — Parent Category Market",
		forecastComparison: "Market Forecast Comparison",
		org: "Research Firm",
		marketForecast: "Market Forecast",
		forecastYear: "Forecast Year",
		scenario: {
			"base-case": "Base",
			optimistic: "Optimistic",
			conservative: "Conservative",
		},
	},
	section04: {
		title: "Technology Timeline",
		searchKeywords: "Search Keywords Used",
		phases: "Technology Development Phases",
		annualTrend: "Annual Paper and Patent Trends",
		year: "Year",
		papers: "Papers",
		patents: "Patents",
		events: "Key Event",
		eventTimeline: "Key Event Timeline",
		keyPapers: "Key Papers",
		topAssignees: "Top Patent Assignees",
		dataSource: "Data source: ",
		openDoi: "Open DOI link",
	},
	section05: {
		title: "Technology Structure",
		commercialized: "A Commercialized",
		demonstrated: "B Demonstrated",
		basicResearch: "C Basic Research",
		blank: "D White Space",
		notViable: "E Not Viable",
		principleMapRef: "Principle map ref: ",
		scope: "Scope Declaration",
		broadDef: "Broad Definition",
		narrowDef: "Narrow Definition for This Analysis",
		adoptedScope: "Adopted Scope",
		excluded: "Excluded Adjacent Technologies",
		mechanismAndSubprocess: "Central Mechanism and Subprocesses",
		centralMechanism: "Central Mechanism",
		required: "Required",
		optional: "Optional",
		principleAxes: "Principle Axes",
		linkedSubprocess: "Linked Subprocess",
		principleMap: "Principle Map",
		combinations: "combinations",
		selectBadge: "Select a classification badge to show matching combinations.",
		trlDefs: "TRL Definitions",
		trlAssessment: "TRL Assessment by Technology Method",
	},
	section06: {
		title: "Challenges",
		mainChallenges: "Main Challenges",
		barrier: "Barrier: ",
		risk: {
			tech: "Technical",
			economic: "Economic",
			regulatory: "Regulatory",
			social: "Social",
			geopolitical: "Geopolitical",
		},
	},
	section07: {
		title: "Public Support",
		programs: "Available Public Support Programs",
		openApply: "Open application page",
	},
}

export function useQueryReportLabels() {
	const { i18n } = useTranslation()
	return useMemo(() => (i18n.language === "en" ? EN : JA), [i18n.language])
}
