source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 8.0"
gem "pg", "~> 1.5"
gem "good_job", "~> 4.0"
gem "faraday", "~> 2.9"
gem "puma", "~> 6.4" # required by Rails but we only run worker

group :development, :test do
  gem "debug", platforms: %i[mri]
end
